dashboard:
  usermanagment:
    label: Users
    uri:
    class: user
    order: 2
    pages:
      create:
        label: Add New User
        module: users
        controller: management
        action: create
        route: default
      edit:
        label: All Users
        module: users
        controller: management
        action: index
        route: default
  statistic:
    pages:
      users:
        label: Users
        module: users
        controller: management
        action: stats
        route: default
toppanel:
  userlogout:
    label: Sign Out
    route: logout
    module: users
    controller: login
    action: logout
    order: 10
  userlogin:
    label: sign In
    route: login
    module: users
    controller: login
    action: index
    order: 20
  userProfile:
    label: Profile
    route: default
    module: users
    controller: profile
    action: index
    order: 30
  registration:
    label: Sign Up
    route: default
    module: users
    controller: register
    action: index
    order: 40
#-------------------------------
leftbar:
  Changepassword:
    label: Change Passowrd
    route: default
    module: users
    controller: login
    action: recover-password
    class: last
    order: 40
  Mytravelinfo:
    label: Travel Preferences
    route: default
    module: users
    controller: profile
    action: travelpreferences
    order: 30
  personallinfo:
    label: Personal Info
    route: default
    module: users
    controller: profile
    action: personal
    order: 20
  accountinfo:
    label: Account Info
    route: default
    module: users
    controller: profile
    action: account
    order: 10
  dashboard:
    label: My Dashboard
    route: default
    module: users
    controller: profile
    action: index
    class: current
    order: 5
    