header:
  poimenu:
    label: Point Of Interests
    route: poiprofile
    class: poi
    order: 10
#-------------------------------
leftbarpoi:
  newstay:
    label: Add New Stay
    route: default
    module: poi
    controller: profile
    action: index
    class: current
    order: 10
  neweat:
    label: Add New Eat
    route: default
    module: poi
    controller: profile
    action: index
    order: 20
  newthings:
    label: Add New Things
    route: default
    module: poi
    controller: profile
    action: index
    order: 30
  masterinfo:
    label: Edit POI
    route: default
    module: poi
    controller: profile
    action: generalinfo
    order: 40
  relatedpoi:
    label: Edit Related POIs
    route: default
    module: poi
    controller: profile
    action: related
    order: 50
    

    