poiprofile:
  route: poi/Profile
   defaults:
    module: poi
    controller: profile
    action: index
generalinfo:
  route: poi/generalinfo/:id
   defaults:
    module: poi
    controller: profile
    action: generalinfo
    id:0
related:
  route: poi/related/:id
   defaults:
    module: poi
    controller: profile
    action: related
    id:0
view:
  route: poi/view/:id
   defaults:
    module: poi
    controller: profile
    action: view
    id:0
thngsparam:
  route: poi/thngsparam/:id/:param_id
   defaults:
    module: poi
    controller: profile
    action: thngsparam
    id:0
    param_id:0
addStay:
  route: poi/addstay
   defaults:
    module: poi
    controller: profile
    action: addstay
addeEat:
  route: poi/addeat
   defaults:
    module: poi
    controller: profile
    action: addeat
addThings:
  route: poi/addthings
   defaults:
    module: poi
    controller: profile
    action: addthings

