<?php
$form = $this->form;
?>
<form id="<?php echo $form->getName();?>"
		name="<?php echo $form->getName();?>" 
		enctype="multipart/form-data"
		method="<?php echo $form->getMethod();?>"
		action="<?php echo $form->getAction();?>">

<div class="main-container col2-left-layout">
    <div class="main">
        <div class="col-main">
        <div class="col-main-container">
        <div class="dashboard">
         <div class="page-title">
                    <h2><?php echo $this->title;?></h2>
         </div>
        <div class="box-account box-info">
<ul class="form-list">
   <li class="fields">
    <div class="field ">
        <label for="login">User Name</label>
        <div class="input-box">
        <?php echo $form->getElement('login');?>
        </div>
    </div>
    <div class="field">
        <label for="password">Password</label>
        <div class="input-box">
        <?php echo $form->getElement('password');?>
        </div>
    </div>
    </li>
    <li class="fields">
    <div class="field">
        <div class="input-box">
        <?php echo $form->getElement('rememberMe');?>
        </div>
    </div>
    </li>
</ul>
  <div class="buttons-set">
       <?php echo $form->getElement('submit');?>
  </div>
<p class="small">
    <a href="<?php echo $this->url(array('module' => 'users',
                                         'controller'=>'register',
                                         'action'=>'index'),
                                   'default'); ?>"><?php echo $this->__('Register now')?></a> |
    <a href="<?php echo $this->url(array('module' => 'users',
                                         'controller'=>'register',
                                         'action'=>'forget-password'),
                                   'forgetPassword'); ?>"><?php echo $this->__('Forget Password')?></a>

    <?php if ($this->google):?>        |
        <a href="<?php echo $this->url(array('module' => 'users', 'controller' => 'login', 'action' => 'oauth', 'type' => 'google'), 'default');?>">
            <?php echo $this->__('Sign in with Google')?>
        </a>
    <?php endif;?>

    <?php if ($this->twitter):?>        |
        <a href="<?php echo $this->url(array('module' => 'users', 'controller' => 'login', 'action' => 'oauth', 'type' => 'twitter'), 'default');?>">
            <?php echo $this->__('Sign in with Twitter')?>
        </a>
    <?php endif;?>

    <?php if ($this->facebook):?>        |
        <?php echo $this->fbConnect()->login(
            $this->__('Login with Facebook'),
            array('email', 'user_checkins'),
            $this->url(array('module' => 'users', 'controller' => 'login', 'action' => 'oauth', 'type' => 'facebook'), 'default')
        );?>
    <?php endif;?>
</p>
  </div>
    </div>
 </div>
</div>
</div>
</div>
</form>

