mvc:
  users:
    api:
      allow: guest
    index:
      allow: user
    login:
      allow: guest
      index:
        allow: guest
        deny: user
      recoverPassword:
        allow: user
        deny: guest
      logout:
        allow: user
        deny: guest
      recoverpassword:
        allow: guest
        deny: user
    profile:
      allow: user
      deny: guest
    register:
      allow: guest
      deny: user
    management:
      allow: admin