<?php 
$into_param= $this->intro_param;
$stay_list=$this->stay_list;
$eat_list=$this->eat_list;
$things_list=$this->things_list;
$days=$into_param['exp_days'];
$days_detail=$this->days_detail;
$exp_id=$this->exp_id;
$exp_user_id=$this->exp_user_id;

$form=$this->form;

?>
<script type="text/javascript">
loadScript(); 
</script>

<div class="main-container col2-layout-expshare">
<div class="main">
<div class="col-right">
<div id="feedback"></div>
</div>

<div class="col-main">
<div class="col-main-container">
<div class="box-info">
<div class="box-head ">
    <h2>Related Pois of My Hotel</h2>
</div>

<input id="thispoi_lat" name = "thispoi_lat" type="hidden" value="24.4958385">
<input id="thispoi_lon" name = "thispoi_lon" type="hidden" value="54.60401209999998">
<input id="thispoi_id" name = "thispoi_id" type="hidden" value="13">
<input id="page_id" name = "page_id" type="hidden" value="#day_1 li">

<div class="container">

<!-- Dragable-->

<div class = "poi-tab-wrapper">
<div class="index-tabs">
<!-- ----------------------Col 1   -->
<div id="tab-1" class="tab tab-1 tab-active">
<p class="tab-button"><span>&nbsp;</span>Stay</p>
<div class="container">

<div class="box-info">
<div class="input-search-box">
<input type="text" name="staysearch" id="staysearch" value=""class="input-search">
<input id="tw-input-submit" type="submit" value="" disabled="disabled"/>
</div>
<div id="divselectablelist" class="ui-widget ui-helper-clearfix">
<ul id="staylist" class="poilist  ui-helper-reset ui-helper-clearfix">
<?php 
$i=0;
foreach ($stay_list as $stay)
{?>
    <li id=<?php echo $stay['poi_id'];?> class="ui-widget-content ui-corner-tr" 
        data-lat=<?php echo $stay['poi_lat']?> data-lon = <?php echo $stay['poi_lon']?> data-poitype=<?php echo $stay['poi_type']?>
        style="cursor:move;">
        <h4><?php echo $stay['poi_name']?></h4>
        <a href="" title="View the POI" class="ui-icon ui-icon-zoomin ">View the POI</a>
		<a id = "poilist-icon" href="" title="Push to Related POI" class="ui-icon ui-icon-arrowreturnthick-1-s">Push to Related POI</a>
	</li>
    <?php }
    
?>
</ul>
</div>
</div>
</div>
</div>
<!-- ----------------------Col 2   -->
<div class="tab tab-2">
<p class="tab-button"><span></span>Eat, Dring and Things to do</p>
<div id="tab-2" class="container">
<div class= "col2-set">
<div class="col-1">
<div class="box-info">
<div class="input-search-box">
<input type="text" name="eatsearch" id="eatsearch" value="" class="input-search">
<input id="tw-input-submit" type="submit" value="" disabled="disabled"/>
</div>
<div id="divselectablelist" class="ui-widget ui-helper-clearfix">
<ul id="eatlist" class="poilist ui-helper-reset ui-helper-clearfix">
<?php 
$i=0;
foreach ($eat_list as $eat)
{?>
    <li id=<?php echo $eat['poi_id'];?> class="ui-widget-content ui-corner-tr" 
        data-lat=<?php echo $eat['poi_lat']?> data-lon = <?php echo $eat['poi_lon']?> data-poitype=<?php echo $eat['poi_type']?>
        style="cursor:move;">
        <h4><?php echo $eat['poi_name']?></h4>
        <a href="" title="View the POI" class="ui-icon ui-icon-zoomin ">View the POI</a>
		<a id = "poilist-icon" href="" title="Push to Related POI" class="ui-icon ui-icon-arrowreturnthick-1-s">Push to Related POI</a>
	</li>
    <?php }
    
?>
</ul>
</div>
</div>
</div>
<!-- ----------------------Col 3   -->
<div class="col-2">
<div class="box-info">
<div class="input-search-box" >
<input type="text" name="thingssearch" id="thingssearch" value="" class="input-search">
<input id="tw-input-submit" type="submit" value="" disabled="disabled"/>
</div>
<div id="divselectablelist" class="ui-widget ui-helper-clearfix">
<ul id="thingslist" class="poilist ui-helper-reset ui-helper-clearfix">
<?php 
$i=0;
foreach ($things_list as $things)
{?>
    <li id=<?php echo $things['poi_id'];?> class="ui-widget-content ui-corner-tr" 
        data-lat=<?php echo $things['poi_lat']?> data-lon = <?php echo $things['poi_lon']?> data-poitype=<?php echo $things['poi_type']?>
        style="cursor:move;">
        <h4><?php echo $things['poi_name']?></h4>
        <a href="" title="View the POI" class="ui-icon ui-icon-zoomin ">View the POI</a>
		<a id = "poilist-icon" href="" title="Push to Related POI" class="ui-icon ui-icon-arrowreturnthick-1-s">Push to Related POI</a>
	</li>
    <?php }
    
?>
</ul>
</div>
</div>
</div>
</div>
</div>
</div>
</div>

</div>
</div>
</div> <!-- box info    -->

</div> <!-- col-main-container   -->
</div> <!-- col-main   -->



</div>
</div>
<div class="relatedpoi">
<div class="container">
<div class="col3-set">
<div id = "day_summary" class = "day_summary">
</div>
<div class="col-selectedpoi">
<div id="wrapper">
<div id="horizontal">
<div id="myScroll">
<?php 
for ($i = 1; $i <= $days; $i++) 
{?>
<div class="scrollEl">
<div class="box-info">
<div class ="box-title">
<h3>Day <?php echo $i;?></h3>
</div>
<div id="divselectablelist" class="ui-widget ui-helper-clearfix">
<ul id = "day_<?php echo $i;?>"  class="poilist ui-helper-reset ui-helper-clearfix">
<?php 
foreach ($days_detail as $related)

{   
    if ($related['exp_day_no'] == $i){
?>

    <li id=<?php echo $related['exp_poi_id'];?> class="ui-widget-content ui-corner-tr"
        data-lat=<?php echo $related['poi_lat']?> data-lon = <?php echo $related['poi_lon']?> data-poitype=<?php echo $related['poi_type']?>
        style="cursor:move;">
        <h4><?php echo $related['poi_name']?></h4>
        <a href="" title="View the POI" class="ui-icon ui-icon-zoomin">View the POI</a>
		<a id = "poilist-icon2" href="" title="Push to Related POI" class="ui-icon ui-icon-arrowreturnthick-1-n">Push to Related POI</a>
        <a id = "poilist-icon3" href="" title='Add your feedback' class='ui-icon ui-icon-document'>Add Your Feedback</a>
    </li>
<?php } 
}  ?>

</ul>
</div>
</div>
</div>

<?php }?>
</div>
</div>
    <div id="controls">
      <div class="first">first</div><div class="prev">prev</div>
      <div class="next">next</div><div class="last">last</div>
      <div class="pageIndex"></div>
      <div class="positiondisplay">AAA</div>
    </div>
</div>
</div> 
<div class="col-maps">
<div id="map_canvas2" class="box-info map_canvas3">

</div>
</div>
</div>
</div>
</div>
<!-- ---------------------- end of Related    -->
<div class="main-container">
</div>
<div id="tooltip" class="tooltip"></div>


<div id="extruderTop" class="{title:'Help me', url:'parts/extruderTop.html'}">
<div class="content"> </div>
</div>
<div id="extruderLeft" class="a {title:'Summary'}">
<div class="content"> 

<div class="box-info">
<ul class="form-list">
   <li class="fields">
    <div class="field ">
         <p>Title</p>
         <div class="input-box">
    	    <?php echo $into_param['exp_title'];?>
         </div>
         </div>
   </li>
     <hr>
   <li class="fields">
    <div class="field ">
         <p>Number of Days</p>
             <div class="input-box">
    	    <?php echo $into_param['exp_days'];?>
         </div>
         </div>
   </li>
   <hr>
   <li class="fields">
    <div class="field ">
         <p>Number of Adults</p>
             <div class="input-box">
    	    <?php echo $into_param['exp_adults'];?>
         </div>
         </div>
   </li>
   <hr>
   <li class="fields">
    <div class="field ">
         <p>Number of Childs</p>
             <div class="input-box">
    	    <?php echo $into_param['exp_childs'];?>
         </div>
         </div>
   </li>
   <hr>
   <li class="fields">
    <div class="field ">
         <p>City</p>
             <div class="input-box">
    	    <?php echo $into_param['exp_city'];?>
         </div>
         </div>
   </li>
   </ul>
</div>
</div>
</div>
<div id="extruderRight" class="{title:'Direction Map'}">
<div id="contentright" class="content"> 
</div>

</div>


<script>
  $(document).ready(function() {
	    <?php 
	    $a="#day_1";
	    $ali="#day_1 li";
	    for ($i = 2; $i <= $days; $i++) {
            $a=$a.',#day_'.$i;
            $ali=$ali.',#day_'.$i.' li';
            }	    
	    ?>
		var $stay    = $( "#staylist" );
		var $eat    = $( "#eatlist" );
		var $things    = $( "#thingslist" );
		var current_page_index=1; 
		var dragops = {
				connectWith: "<?php echo $a;?>",
				revert:true,
				};
		var dropops = {
				connectWith: "#staylist, #eatlist, #thingslist",
				revert:true,
				update: function(event, ui) {
					var mapid = ui.item.attr("id");
				    var lat2 = ui.item.attr("data-lat");
					var lon2 = ui.item.attr("data-lon");


//					relateItem( ui.item );
//					addMarker(lat2,lon2,'r',mapid);
					}
				};
		$( "#thingslist" ).sortable(dragops);
		$( "#eatlist" ).sortable(dragops);
		$( "#staylist" ).sortable(dragops);
	    <?php 
	            for ($i = 1; $i <= $days; $i++) {
	                echo '$("#day_'.$i.'").sortable(dropops);';
	            }	    
	    ?>
	    


	    
	    $("#staysearch").keyup(function(){
	        var text = $(this).val();
	        $('#staylist li').each(function(){
	             if($(this).text().toUpperCase().indexOf(text.toUpperCase()) == -1)
	                 $(this).hide();
	             else
	                $(this).show();
	        });     
	    });
	    $("#eatsearch").keyup(function(){
	        var text = $(this).val();
	        $('#eatlist li').each(function(){
	            if($(this).text().toUpperCase().indexOf(text.toUpperCase()) == -1)
	                $(this).hide();
	             else
	                $(this).show();});     
	    });
	    $("#thingssearch").keyup(function(){
	        var text = $(this).val();
	        $('#thingslist li').each(function(){
	            if($(this).text().toUpperCase().indexOf(text.toUpperCase()) == -1)
	                $(this).hide();
	             else
	                $(this).show();});     
	    });
	    function viewItem($item) {
			    var id = $item;
			    var a = '/poi/view/'+id;
			    $.ajax({
			        url: a,
			        success: function(data){
			            var divtooltip = document.getElementById("contentright");
			            divtooltip.innerHTML = data;
					    $('#extruderRight').openMbExtruder(true);
					    $('#extruderRight').openPanel();
},
					    
	      	});
				    
		};
		// Push to related function
		var move_up_icon = "<a href='' title='take the POI back' class='ui-icon ui-icon-arrowreturnthick-1-n'>Take the POI Back</a>";
		
		var add_info_icon = "<a href='' title='Add your feedback' class='ui-icon ui-icon-document'>Add Your Feedback</a>";
		function relateItem( $item ) {
		$item.fadeOut(function() {

		       var $index= $('#myScroll').get(0).idx;
		       var $related= "#day_"+$index;
				$item.find( "a.ui-icon-arrowreturnthick-1-s" ).remove();
				$item.append( move_up_icon,add_info_icon).appendTo( $related ).fadeIn(function() {});
			});
	    var $index= $('#myScroll').get(0).idx;
	    var $related= "#day_"+$index;
		var order = $($related).sortable("toArray");
	    addpoiRow($item,'insert',order);
		}


		// get feedback 
		function getfeedback( $item ) {
		    var id = $item;
            var tooltipvalues = ['bad', 'poor', 'ok', 'good', 'super'];
		    var a = '/exp/sharepoiexp/'+id+'/'+<?php echo $exp_id;?>;
		    savefeedback();
		    $.ajax({
		        url: a,
		        success: function(data){
		            var digops = {
           			autoOpen: false,
           	    	resizable : false,
   	        		show: true,
   	        		hide: true,
   	        		height: 300,
   	                width: 800,
   	        	    };
		            var divtooltip = document.getElementById("feedback");
		            divtooltip.innerHTML = data;
				    $('div.rateit').bind('over', function (event, value) { $(this).attr('title', tooltipvalues[value-1]); });
			      	$(function () { $('div.rateit').rateit(); });
			      	 $( "#accordion" ).accordion({heightStyle: "fill"});
},
				    
     	});
}
			
		// image recycle function
		var move_icon_down= "<a href='' title='Relat this POI' class='ui-icon ui-icon-arrowreturnthick-1-s'>Delete image</a>";
		function recycleItem( $item,$itemtype ) {
		    $item.fadeOut(function() {
		        $item.find( "a.ui-icon-arrowreturnthick-1-n,a.ui-icon-document" ).remove();
		        if ($itemtype=='Stay'){
		            $item.append( move_icon_down).appendTo( $stay).fadeIn(function() {});}
		        else if ($itemtype=='Eat'){
		            $item.append( move_icon_down).appendTo( $eat).fadeIn(function() {});}
		        else if ($itemtype=='Things'){
		            $item.append( move_icon_down).appendTo( $things).fadeIn(function() {});}
		    });
		    var mapid= $item.attr("id");
		    removeMarker(mapid);
		    var $index= $('#myScroll').get(0).idx;
		    var $related= "#day_"+$index;
		    var order = $($related).sortable("toArray");		    
		    addpoiRow($item,'delete',order);
		
		};
		
		$( "#staylist li, #eatlist li, #thingslist li,<?php echo $ali;?>" ).click(function(event ) {
			var $item = $( this ),
				$target = $( event.target ),
				$itemid=$( this ).attr('id'),
		        $itemtype=$( this ).attr('data-poitype');
				
			if ( $target.is( "a.ui-icon-arrowreturnthick-1-s" ) ) 
			{
			    var poi_lat = $( this ).attr("data-lat");
				var poi_lon = $( this ).attr("data-lon");
				addMarker(poi_lat,poi_lon,'r',$itemid);
			    relateItem( $item );
			} else if ( $target.is( "a.ui-icon-zoomin" ) ) {
				viewItem( $itemid );
			} else if ( $target.is( "a.ui-icon-arrowreturnthick-1-n" ) ) {
				recycleItem( $item,$itemtype );
			} else if ( $target.is( "a.ui-icon-document" ) ) {
				getfeedback($itemid);
			}
			return false;
		});
		
		function addpoiRow($item,action,order) {
		    var index= $('#myScroll').get(0).idx;
		    var poi_id = $item.attr("id");
		    var relatedtype = $item.attr("data-poitype");
		    var lat = $item.attr("data-lat");
		    var lon = $item.attr("data-lon");
		    var lon = $item.attr("data-lon");
		    var tobeposted = {
		    		exp_id: <?php echo $exp_id;?> ,
		    		exp_day_no:index,
		    		exp_poi_id:poi_id,
		    		exp_poi_lat:lat,
		    		exp_poi_lon:lon,
		    		exp_poi_type:relatedtype,
		    		exp_poi_order:999,
		    		order:order,
		    		action:action
		    };
		    $.ajax({
	    	  type: 'POST',
	    	  url:'/exp/shareexp/savepoi',
	    	  data: tobeposted,
		      success: function(retdata){}
			});
	};
		

// end of doc ready
  
function toRad(value){
	    return value* Math.PI / 180;
};	

function calcdist(lat1,lon1,lat2,lon2){
	var R = 6371; // Radius of the earth in km
    var dLat = toRad((lat2-lat1));  // Javascript functions in radians
    var dLon = toRad((lon2-lon1));
    callat1=toRad(lat1);
    callat2=toRad(lat2);
    
    var a = Math.sin(dLat/2) * Math.sin(dLat/2) +
        Math.cos(callat1) * Math.cos(callat2) * 
        Math.sin(dLon/2) * Math.sin(dLon/2); 
    var c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a)); 
    var d = R * c; // Distance in km
    d = Math.round(d);
    return d;
    };

    function savesumndfeed (page_id,index) {
        var exppoi_param_id = new Array();
        var exppoi_param_value = new Array();
        var exppoi_param_detail = new Array();
        var form_set=false;
        var form_exppoi=document.getElementById("ExppoiForm");
	    if (typeof(form_exppoi) != 'undefined' && form_exppoi!= null)
	    {
		    j=0;
		    k=0;
		    m=-1;
		    checked=false;
		    average_time_loop=false;
		    form_set=true;
        for (var i=0;i<form_exppoi.length;i++)
    	  {
    	  if (form_exppoi.elements[i].id.substring(0,21)=='exp_poi_average_time-')
    	    {
    		  average_time_loop=true;
        		if (form_exppoi.elements[i].checked)
        		{
            		m++;
            		checked=true;
            		exppoi_param_id[m]   ='exp_poi_average_time';
            		exppoi_param_value[m]=form_exppoi.elements[i].value;
            		continue;
            	}
        		else
            		continue;
    	    
    	    }
	        if (form_exppoi.elements[i].id.substring(0,14)=='poi_amenities-')
    	    {
        		exppoi_param_detail[j]=[];
        	    exppoi_param_detail[j][k++]=form_exppoi.elements[i].value;
    	    	continue;
        	    
        	}
    	    if (form_exppoi.elements[i].id.substring(0,19)=='poi_amenities_desc-')
    	    {
        	    exppoi_param_detail[j][k++]=form_exppoi.elements[i].value;
    	    	continue;
        	    
        	}
        	if (form_exppoi.elements[i].id.substring(0,7)=='rateit-')
    	    {
        	    exppoi_param_detail[j][k++]=form_exppoi.elements[i].value;
    	    	continue;
        	    
        	}
    	    if (form_exppoi.elements[i].id.substring(0,10)=='shortdesc-')
    	    {
        	    exppoi_param_detail[j++][k++]=form_exppoi.elements[i].value;
        	    k=0;
    	    	continue;
    	    }
    		if (!checked && average_time_loop)
    	  	{
    	      	m++;
    	  		exppoi_param_value[m]=0;
    	    	exppoi_param_id[m]   ='exp_poi_average_time';
    	    	continue;
    	    }
    	    m++;
    	    exppoi_param_id[m]   =form_exppoi.elements[i].id;
    		exppoi_param_value[m]=form_exppoi.elements[i].value;
    	    }
	    }
        var transtype = document.getElementById('exp_trans_type');
	    if (typeof(transtype ) != 'undefined' && transtype != null)
	    {
		    var transtype = document.getElementById('exp_trans_type').value;
	    }
        var trans_cost = document.getElementById('exp_trans_cost');
	    if (typeof(trans_cost ) != 'undefined' && trans_cost != null)
	    {
	        var trans_cost = document.getElementById('exp_trans_cost').value;
	    }
        var trans_comment= document.getElementById('exp_trans_comment');
	    if (typeof(trans_comment) != 'undefined' && trans_comment!= null)
	    {
	        var trans_comment= document.getElementById('exp_trans_comment').value;
	    }
        var day_cost= document.getElementById('exp_day_cost');
	    if (typeof(day_cost) != 'undefined' && day_cost!= null)
	    {
	        var day_cost= document.getElementById('exp_day_cost').value;
	    }
	    
	    var tobeposted = {
	    		exp_id: <?php echo $exp_id;?> ,
	    		exp_day_no:page_id,
	    	    exp_next_day_no:index,
	    		exp_trans_type:transtype,
	    		exp_trans_cost :trans_cost ,
	    		exp_trans_comment:trans_comment,
	    		exp_day_cost:day_cost,
	    		exppoi_id:exppoi_param_id,
	    		exppoi_value:exppoi_param_value,
	    		exppoi_detail:exppoi_param_detail,
	    };
	    $.ajax({
    	  type: 'POST',
    	  url:'/exp/shareexp/savesumndfeed',
    	  data: tobeposted,
	      success: function(retdata){
		  var divsummary = document.getElementById("day_summary");
	      divsummary.innerHTML = retdata;}
		});
    };     


    function savefeedback () {
        var exppoi_param_id = new Array();
        var exppoi_param_value = new Array();
        var exppoi_param_detail = new Array();
        var form_set=false;
        var form_exppoi=document.getElementById("ExppoiForm");
	    if (typeof(form_exppoi) != 'undefined' && form_exppoi!= null)
	    {
		    j=0;
		    k=0;
		    m=-1;
		    checked=false;
		    average_time_loop=false;
		    form_set=true;
        for (var i=0;i<form_exppoi.length;i++)
    	  {
    	  if (form_exppoi.elements[i].id.substring(0,21)=='exp_poi_average_time-')
    	    {
    		  average_time_loop=true;
        		if (form_exppoi.elements[i].checked)
        		{
            		m++;
            		checked=true;
            		exppoi_param_id[m]   ='exp_poi_average_time';
            		exppoi_param_value[m]=form_exppoi.elements[i].value;
            		continue;
            	}
        		else
            		continue;
    	    
    	    }
	        if (form_exppoi.elements[i].id.substring(0,14)=='poi_amenities-')
    	    {
        		exppoi_param_detail[j]=[];
        	    exppoi_param_detail[j][k++]=form_exppoi.elements[i].value;
    	    	continue;
        	    
        	}
    	    if (form_exppoi.elements[i].id.substring(0,19)=='poi_amenities_desc-')
    	    {
        	    exppoi_param_detail[j][k++]=form_exppoi.elements[i].value;
    	    	continue;
        	    
        	}
        	if (form_exppoi.elements[i].id.substring(0,7)=='rateit-')
    	    {
        	    exppoi_param_detail[j][k++]=form_exppoi.elements[i].value;
    	    	continue;
        	    
        	}
    	    if (form_exppoi.elements[i].id.substring(0,10)=='shortdesc-')
    	    {
        	    exppoi_param_detail[j++][k++]=form_exppoi.elements[i].value;
        	    k=0;
    	    	continue;
    	    }
    		if (!checked && average_time_loop)
    	  	{
    	      	m++;
    	  		exppoi_param_value[m]=0;
    	    	exppoi_param_id[m]   ='exp_poi_average_time';
    	    	continue;
    	    }
    	    m++;
    	    exppoi_param_id[m]   =form_exppoi.elements[i].id;
    		exppoi_param_value[m]=form_exppoi.elements[i].value;
    	    }
	    }
	    if(form_set)
	    {
	    var tobeposted = {
	    		exp_id: <?php echo $exp_id;?> ,
	    		exppoi_id:exppoi_param_id,
	    		exppoi_value:exppoi_param_value,
	    		exppoi_detail:exppoi_param_detail,
	    };
	    $.ajax({
    	  type: 'POST',
    	  url:'/exp/shareexp/savefeedback',
    	  data: tobeposted,
	      success: function(retdata){}
		});
	    }
    };     

    $(window).bind('beforeunload', function(){ 
	savesumndfeed(current_page_index,$('#myScroll').get(0).idx);
    return '';
    });
    $(function(){
      if (self.location.href == top.location.href){
        $("body").css({font:"normal 13px/16px 'trebuchet MS', verdana, sans-serif"});
      }

      $("#myScroll").mbScrollable({
        width:260,
        elementsInPage:1,
        elementMargin:0,
//        shadow:"#999 2px 2px 2px",
        height:"340px",
        controls:"#controls",
        slideTimer:600,
        autoscroll:false,
        scrollTimer:4000,
				changePageCallback:function(){
					var positiondisplay= $('#myScroll').get(0).idx+'/'+$('#myScroll').get(0).totalPages;
					$('#controls .positiondisplay').html(positiondisplay);
				    var currentpage= '#day_'+$('#myScroll').get(0).idx+' li';
				    savesumndfeed(current_page_index,$('#myScroll').get(0).idx);
					addrelatedMarkers(currentpage);
		            var divtooltip = document.getElementById("feedback");
		            divtooltip.innerHTML = '';
					
					current_page_index= $('#myScroll').get(0).idx;
},
				loadCallback:function(){
					var positiondisplay= $('#myScroll').get(0).idx+'/'+$('#myScroll').get(0).totalPages;
					current_page_index= $('#myScroll').get(0).idx;
					savesumndfeed(current_page_index,current_page_index);
					$('#controls .positiondisplay').html(positiondisplay);
				}
      });

      setTimeout(function(){$("#wrapper").fadeIn();},2);
    });

				if (self.location.href == top.location.href){
					$("body").css({font:"normal 13px/16px 'trebuchet MS', verdana, sans-serif"});
					var logo=$("<a href='http://pupunzi.com'><img id='logo' border='0' src='http://pupunzi.com/images/logo.png' alt='mb.ideas.repository' style='display:none;'></a>").css({position:"absolute"});
					$("body").prepend(logo);
					$("#logo").fadeIn();
				}

					$("#extruderTop").buildMbExtruder({
						position:"top",
						positionFixed: true,
						width:350,
						extruderOpacity:1,

						autoCloseTime:0,
						autoOpenTime:1000,
						hidePanelsOnClose:false,
						onExtOpen:function(){},
						onExtContentLoad:function(){$("#extruderLeft").openPanel();},
						onExtClose:function(){}
					});


					$("#extruderLeft").buildMbExtruder({
						position:"left",
						width:300,
						extruderOpacity:.8,
						
						hidePanelsOnClose:false,
						accordionPanels:false,
						onExtOpen:function(){},
						onExtContentLoad:function(){$("#extruderLeft").openPanel();},
						onExtClose:function(){}
					});

					$("#extruderLeft2").buildMbExtruder({
						position:"left",
						width:300,
						positionFixed:false,
						top:0,
						extruderOpacity:.8,
						onExtOpen:function(){},
						onExtContentLoad:function(){},
						onExtClose:function(){}
					});

					$("#extruderRight").buildMbExtruder({
						position:"right",
						width:300,
						positionFixed:true,
						extruderOpacity:.8,
						textOrientation:"tb",
						onExtOpen:function(){},
						onExtContentLoad:function(){},
						onExtClose:function(){}
					});

				$.fn.changeLabel=function(text){
					$(this).find(".flapLabel").html(text);
					$(this).find(".flapLabel").mbFlipText();
				}

			//},1000);
  });
		
	</script>
	
	
	
 <style type="text/css">
		.wrapper{
			position:relative;
			font-family:Arial, Helvetica, sans-serif;
			padding-top:90px;
			padding-left:50px;
			width:80%;
			margin:auto
		}
		.wrapper .text{
			font-family:Arial, Helvetica, sans-serif;
			padding-top:50px;
		}
		.wrapper h1{
			font-family:Arial, Helvetica, sans-serif;
			font-size:26px;
		}
		.longText{
			margin-top:20px;
			width:600px;
			font:18px/24px Arial, Helvetica, sans-serif;
			color:gray;
		}
		span.btn{
			padding:10px;
			display:inline-block;
			cursor:pointer;
			font:12px/14px Arial, Helvetica, sans-serif;
			color:#aaa;
			background-color:#eee;
			-moz-border-radius:10px;
			-webkit-border-radius:10px;
			-moz-box-shadow:#999 2px 0px 3px;
			-webkit-box-shadow:#999 2px 0px 3px;
		}
		span.btn:hover{
			background-color:#000;
		}

			/*
									custom style for extruder
									*/

		.extruder.left.a .flap{
			font-size:18px;
			color:white;
			top:0;
			padding:10px 0 10px 10px;
			background:#772B14;
			width:30px;
			position:absolute;
			right:0;
			-moz-border-radius:0 10px 10px 0;
			-webkit-border-top-right-radius:10px;
			-webkit-border-bottom-right-radius:10px;
			-moz-box-shadow:#666 2px 0px 3px;
			-webkit-box-shadow:#666 2px 0px 3px;
		}

		.extruder.left.a .content{
			border-right:3px solid #772B14;
			background:rgba(255,255,255,.95);
		}

		.extruder.top .optionsPanel .panelVoice a:hover{
			color:#fff;
			background: url("elements/black_op_30.png");
			border-bottom:1px solid #000;
		}
		.extruder.top .optionsPanel .panelVoice a{
			border-bottom:1px solid #000;
		}

		.extruder.left.a .flap .flapLabel{
			background:#772B14;
		}
	</style>
  <script type="text/javascript">
jQuery(document).ready(function($){
	if(jQuery.browser.msie && $.browser.version < 8) 
		$('input[type=radio],[type=checkbox]').on('click', 
				function(){ $(this).trigger('change'); });
	jQuery('.index-tabs .tab-2 .container').hide();
	jQuery('.index-tabs .tab-button').click(function(){
		jQuery(this).parents('.index-tabs').find('.tab').each(function(){ 
			jQuery(this).removeClass('tab-active'); $('.container', this).hide(); });
		jQuery(this).next('.container').show();
		jQuery(this).parent('div').addClass('tab-active');
	});
	
});
</script>
  