shareexp:
  route: shareexp
   defaults:
    module: exp
    controller: shareexp
    action: index
expsavepoi:
  route: exp/shareexp/savepoi
   defaults:
    module: exp
    controller: shareexp
    action: savepoi
exppoi:
  route: exp/sharepoiexp/:poi_id/:exp_id
   defaults:
    module: exp
    controller: shareexp
    action: sharepoiexp
    poi_id:0
    exp_id:0
expsavesummaryandfeedback:
  route: exp/shareexp/savesumndfeed
   defaults:
    module: exp
    controller: shareexp
    action: savesumndfeed
expsavefeedback:
  route: exp/shareexp/savefeedback
   defaults:
    module: exp
    controller: shareexp
    action: savefeedback
    