		
<table>
    <tbody>
    <tr>
        <td>
            <label for="poi_name">Name</label>
        </td>
        <td>
    	    <?php echo $form->getElement('poi_name');?>
    	    <?php echo $form->getElement('poi_id');?>
    	</td>
    </tr>
	<tr>
	    <td>
            <label for="poi_web_site">Web Site</label>
        </td>
        <td>
	        <?php echo $form->getElement('poi_web_site');?>
        </td>
    </tr>
    <tr>
        <td>
            <label for="poi_contact detail">Contact Detail</label>
        </td>
        <td>
            <?php echo $form->getElement('poi_contact_detail');?>
        </td>
    </tr>
    <tr>
        <td>
		    <label for="poi_things_type">Things to Do Type</label>
        </td>
        <td>
        <?php if (isset($poi_id) and !is_null($poi_id))
                echo $form->getValue('poi_things_type');
            else
		        echo $form->getElement('poi_things_type');?>
        </td>
    </tr>
</tbody>
</table>
<table>
        <tr>
            <td>
                <label for="poi_country">Country</label>
            </td>
            <td>
                <?php echo $form->getElement('poi_country');?>
            </td>
            <td>
                <label for="poi_city">City</label>
            </td>
            <td>
                <?php echo $form->getElement('poi_city');?>
                <input id="poi_lat" name = "poi_lat" type="hidden" value="<?php echo $form->getElement('poi_lat')->getValue();?>">
                <input id="poi_lon" name = "poi_lon" type="hidden" value="<?php echo $form->getElement('poi_lon')->getValue();?>">
            </td>
        </tr>
    </table>
    <table>
        <tr>
            <td>
                <label for="poi_area">Area</label>
            </td>
            <td>
                <?php $lat='';
                      $lon='';?>
                <?php echo $form->getElement('poi_area');?>
           </td>
        </tr>
        </table>
<div id="map_canvas"></div>

<script type="text/javascript">
<!--
$(document).ready(function() {
	
	$('.poi_things_type').change(function() {
		var id = $(this).attr("value");
		if (typeof document.getElementsByName("poi_id")[0] != 'undefined') {
		    var poi_id = document.getElementById('poi_id').value;
		} else {
			var poi_id='undefined';
		}
		var a = 'http://myapp/poi/thngsparam/'+poi_id+'/'+id;
	    $.ajax({
	        url: a,
	        success: function(data){
	            var divtab2 = document.getElementById("tabs-2");
	            divtab2 .innerHTML = data;},
	    });	
	});
});
//-->
</script>
