<style>
<!--
.loading {
	margin : 300px;
}
-->
</style>
<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/css/lightbox/lightbox.css" type="text/css" rel="stylesheet"></script>
<div class="box-info">
<div class="box-head ">
    <h2 ><?php echo $form->getValue('poi_name').' Photos';?></h2>
</div>
<ul class="form-list">
   <li class="fields">
    <div class="field ">
         <div class="input-box">
                <?php echo $form->getElement('poi_images');?>
<?php echo $form->getElement('submit');?>
                </div>
    </div>
</li>
</ul>
</div>


<div class="gallery">

<?php 

$imagePath = '/uploads/'.$this->poi_id.'/';
if(count($this->images) > 0) {
	foreach ($this->images as $image) {
		//echo "<pre>";print_r($image);exit;
		print "<div style='float:left;padding:5px;'>";
			print "<a href='".$imagePath.$image['poiimg_path']."' id='img_".$image['poiimg_id']."' alt='".$image['poiimg_title']."' width='70px' height='100px' rel='lightbox[hotel]'>";
			 print "<img src='".$imagePath.$image['poiimg_path']."' alt='".$image['poiimg_title']."' width='70px' height='100px'/>";
			print "</a>";
			
			print "<p><a href='javascript:void(0)' name='del_".$image['poiimg_id']."' class='imgdelete' title = 'Make this image as default'><img src=\"/images/delete.png\" alt=\"Delete\" title = 'Delete Image' height=\"20px\"width=\"20px\"  /></a><span class='spandefault'>";
			if ($image['poiimg_default'] ==  0) {
				print "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";
				print "<a href='javascript:void(0)' name='".$image['poiimg_id']."' class='imgdefault' title = 'Make this image as default'><img src=\"/images/makedefault.png\" alt=\"Make Default\" title = 'Make this image as default' height=\"20px\"width=\"20px\"/></a>";
			}
			print "</span></p>";
		print "</div>";
	}
}
?>

</div>
<input type="hidden" name="img_poi_id" id="img_poi_id" value="<?php echo $this->poi_id;?>"/>
<hr />
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/lightbox/lightbox.js"></script>

<script type="text/javascript">
$(document).ready(function (){
	$(".imgdefault").live("click",function (){
		//alert($(this).attr('name'));
		queryString = "poi_id="+$("#img_poi_id").val ()+"&img_id="+$(this).attr('name');
		$.ajax({
			url : "/poi/profile/makedefault",
			type : "post",
			dataType :'html',
			data : queryString,
			beforeSend : function (xhr) {
				$(".gallery").html ("<span class='loading'><img src='/images/loading.gif' alt='Loading......'/></span>");
			},
			success:function (data){
				$(".gallery").html (data);
			}
		});
	});
	/* Delete Action */
	$(".imgdelete").live("click",function (){
		if(confirm("Are you sure to delete ?")){
			imgid = $(this).attr('name');
			imgid = imgid.split("_");
			imgid = imgid[1];
			//alert("#img_"+imgid);
			
			//imgname = imgname.split("_");
			//imgname = imgname[0];
			queryString = "poi_id="+$("#img_poi_id").val ()+"&img_id="+imgid;
			$.ajax({
				url : "/poi/profile/delete",
				type : "post",
				dataType :'html',
				data : queryString,
				beforeSend : function (xhr) {
					$(".gallery").html ("<span class='loading'><img src='/images/loading.gif' alt='Loading......'/></span>");
				},
				success:function (data){
					location.reload();
					//$(".gallery").html (data);
				}
			});
		}
		
	});
});
</script>

