<?php
$form = $this->form;
$poi_id=$this->poi_id;
$poi_type=$this->poi_type;
?>

<form id="<?php echo $form->getName();?>"
		name="<?php echo $form->getName();?>" class="overlay topLabel page"
		enctype="multipart/form-data"
		method="<?php echo $form->getMethod();?>">

<input type="hidden" name="poi_type" id="poi_type" size="20" value = "<?php echo $poi_type;?>"/>
		
<div class="main-container col2-left-layout">
<div class="main">
<!-- Left Side Bar Starts Here -->	 
<div class="col-left sidebar">
    <div class="block block-sidebar">
    <div class="block-title">
        <strong><span><?php echo $this->leftbartitle;?></span></strong>
    </div>
    <div class="block-content">
    <ul>
    <?php 
    $leftbarcontainer=$this->menuContainer('leftbarpoi');
    $leftsidebar=$this->navigation($leftbarcontainer);
    foreach ($leftbarcontainer as $pages) {
        foreach ($pages as $uid => $page) {
            $liClass = $page->getClass();
            if ($page->getLabel() !== null && $page->isVisible(true)) {
                    if ($page->getLabel() == 'Edit POI')
                        {
                            continue;
                        }
                    if ($page->getLabel() == 'Edit Related POIs')
                        {
                            if ($poi_id !== null)
                                echo '<li class="'.$liClass .'"><a href ='.
                                    '"'.$page->getHref().'/'.$poi_id.'">'.$page->getLabel().'</a></li>', PHP_EOL;
                            else 
                                continue;
                    } else {
                    echo '<li class="'.$liClass .'"><a href ='.
                    '"'.$page->getHref().'">'.$page->getLabel().'</a></li>', PHP_EOL;
                    }
//                echo '<li class="'.$liClass .'">' . $leftsidebar->menu()->htmlify($page) . '</li>', PHP_EOL;
        }
    }
}
?>

</ul>
    </div>
</div>
</div>
<!-- Left Side Bar Starts Here -->	 

<div class="col-main">
<div class="col-main-container">
<div class="page-title">
    <h2><?php echo $this->title;?></h2>
</div> <!-- page title-->
<div class="index-tabs">
<!-- Tab 1-->	 
<div id="tab-1" class="tab tab-1 tab-active">
<p class="tab-button"><span>&nbsp;</span>General Info</p>
<div class="container">
        <?php 
        if ($poi_type=='Stay')
        {
            include '_poiStayinfo.phtml';
        }
        if ($poi_type=='Eat')
        {
            include '_poiEatinfo.phtml';
        }
        if ($poi_type=='Things')
        {
            include '_poiThingsinfo.phtml';
        }
        ?>
</div> <!--  container-->
</div> <!--  tab tab-1 tab-active-->
<!-- Tab 2-->	 
<div class="tab tab-2">
<p class="tab-button"><span></span>Amenities and Facilities</p>
<div id="tab-2" class="container">
        <?php 
        if ($poi_type=='Stay')
        {
        include '_poiStayParams.phtml';
        }
        if ($poi_type=='Eat')
        {
            include '_poiEatParams.phtml';
        }
        if ($poi_type=='Things')
        {
            include 'poithingsparams.phtml';
        }
        ?>
</div>
</div>
<!-- Tab 3-->	 
<div id="tab-3" class="tab tab-3">
<p class="tab-button"><span>&nbsp;</span>Images</p>
<div class="container">
        <?php include '_poiImages.phtml';?>
</div> <!--  container-->
</div> <!--  tab tab-1 tab-active-->

</div>  <!--  index tabs-->
</div> <!--  col main container -->
</div> <!-- col main  -->





</div>
</div>
</form>

<script type="text/javascript">
jQuery(document).ready(function($){
	if(jQuery.browser.msie && $.browser.version < 8) 
		$('input[type=radio],[type=checkbox]').on('click', 
				function(){ $(this).trigger('change'); });
	jQuery('.index-tabs .tab-2 .container').hide();
	jQuery('.index-tabs .tab-3 .container').hide();
	jQuery('.index-tabs .tab-button').click(function(){
		jQuery(this).parents('.index-tabs').find('.tab').each(function(){ 
			jQuery(this).removeClass('tab-active'); $('.container', this).hide(); });
		jQuery(this).next('.container').show();
		jQuery(this).parent('div').addClass('tab-active');
	});
	
});
</script>
		

		

