<style>
#listcontainer {
	width : 900px;
	border :0px solid red;
	min-height: 200px;	
}
.itemlisting {
	width : 850px;
	border :1px dotted green;
	min-height: 200px;
	padding : 10px;
	margin:10px;
}
.hotelimg {
	float:left;
}
.hoteldesc {
	padding-left : 20px;
}
</style>

<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true&libraries=places"></script>

<script type="text/javascript">
var component_form = {
	    'locality': 'long_name',
	    'country': 'long_name',
	  };
function initialize() 
{
    var input = document.getElementById('poititle');
    var autocomplete = new google.maps.places.Autocomplete(input);
    google.maps.event.addListener(autocomplete, 'place_changed', function() 
            {
    	$.ajax({
			url : "/poi/profile/listajax",
			type : "post",
			dataType :'html',
			data : "filterval="+$("#poititle").val (),
			beforeSend : function (xhr) {
				$("#listcontainer").html ("<span class='loading'><img src='/images/loading.gif' alt='Loading......'/></span>");
			},
			success:function (data){
				
				if(data == 'false') {
					$("#listcontainer").html ("");
					$("#newbut").show ();
				}else {
					$("#newbut").hide ();
					$("#listcontainer").html (data);
				}
				//alert(data['pois'][0]['poi_name']);
			}
		});
    	     var place = autocomplete.getPlace();
              document.getElementById('place_name').value= place.name;
              for (var j = 0; j < place.address_components.length; j++) {
                  var att = place.address_components[j].types[0];
                  if (component_form[att]) {
                    var val = place.address_components[j][component_form[att]];
                    document.getElementById(att).value = val;
                  }
                }
              document.getElementById('place_phone').value= place.formatted_phone_number;
              document.getElementById('lat').value= place.geometry.location.lat();
              document.getElementById('lon').value= place.geometry.location.lng();
              document.getElementById('website').value= place.website;
              document.getElementById('type').value= place.types;
              
                
});
}
google.maps.event.addDomListener(window, 'load', initialize);

$(document).ready(function (){
	$("#poititle").keyup(function (){
		loc_name = $("#poititle").val ();
	});
});
</script>
<form method="post" action="/poi/profile/addnew">
<input type="text" name="poititle" id="poititle" size="20" class = "input-text required-entry" placeholder="Enter a location" autocomplete="on"/>
<input type="text" name="place_name" id="place_name" size="20" readonly/>
<input type="text" name="country" id="country" size="20" readonly/>
<input type="text" name="locality" id="locality" size="20" readonly/>
<input type="text" name="place_phone" id="place_phone" size="20" readonly/>
<input type="text" name="lat" id="lat" size="20" readonly/>
<input type="text" name="lon" id="lon" size="20" readonly/>
<input type="text" name="website" id="website" size="20" readonly/>
<input type="text" name="type" id="type" size="20" readonly/>
<br/>
<div id="newbut" style="display:none">
	<input type="submit" name='addnewstay' value="Add New Stay"/>
	<input type="submit" name='addneweat' value="Add New Eat"/>
	<input type="submit" name='addnewthings' value="Add New Things"/>
</div>
</form>
<?php 
//var_dump($this->pois);exit;
$imagePath = '/uploads/';
?>
<div id="listcontainer">
	<?php if(count($this->pois) > 0 ) {?>
		<?php foreach($this->paginator as $poi) {?>
			<?php //echo "<pre>";print_r($poi);exit;?>
			<div class="itemlisting">
				<ul>
					<li class="hotelimg">
					<?php if($poi['default_image']){?>
					
					<img src="<?php echo $imagePath.$poi['poi_id']."/".$poi['default_image']?>" alt="no image" height="160px"width="155px"/>
					<?php } else {?>
					<img src="/images/no_image.gif" alt="no image" height="160px"width="155px"/>
					<?php }?>
					</li>
					<li class="hoteldesc" >
						<h3><?php echo $this->escape($poi['poi_name']);?></h3>
						<p><?php echo $this->escape($poi['groupname']);?></p>
						<p><?php echo $this->escape($poi['stayname']);?></p>
						<p><?php echo $this->escape($poi['poi_area']);?></p>
						<p><?php echo $this->escape($poi['poi_web_site']);?></p>
						<p> <a href="<?php echo '/poi/profile/generalinfo/'.$poi['poi_id'];?>" class ='testaj'>Edit</a></p>
					</li>
				</ul>
			</div>
		<?php }?>
	<?php }?>
</div>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'profile/_p.phtml'); ?>
<script type="text/javascript">
	$(document).ready(function (){
		$("#poititle").keyup(function (){
			filterval = $("#poititle").val ();
			//alert(filterval);
			$.ajax({
				url : "/poi/profile/listajax",
				type : "post",
				dataType :'html',
				data : "filterval="+filterval,
				beforeSend : function (xhr) {
					$("#listcontainer").html ("<span class='loading'><img src='/images/loading.gif' alt='Loading......'/></span>");
				},
				success:function (data){
					if(data == 'false') {
						$("#listcontainer").html ("");
						$("#newbut").show ();
					}else {
						$("#newbut").hide ();
						$("#listcontainer").html (data);
					}
					//alert(data['pois'][0]['poi_name']);
				}
			});
		});
		
	});
</script>
	
