
<?php
if (!isset($form))
    $form = $this->form;
if (!isset($poi_id))
    $poi_id=$this->poi_id;
if (!isset($poi_type))
    $poi_type=$this->poi_type;

$thingsoptions = $form->getElement ( 'poi_things_options' )->getMultiOptions ();
$setvalues= $form->getElement ( 'poi_things_options' )->getValue();
if (!is_array($setvalues))
        $setvalues=explode(' ', $setvalues);
if (isset ( $thingsoptions )) {
	$newrow = true;
	$colnum = 0;
	$totalcol = 2;
	$doit = true;
	?>
<h2>Available Options</h2>
	<table>
		<tbody>
<?php

}

foreach ( $thingsoptions as $key => $value ) {
	if ($newrow) {
		$newrow = false;
		?>
		<tr><?php
	}
	$colnum += 1;
	?>
	<td><label for="poi_things_options-<?php echo $key;?>"><?php echo $value;?></label>
		<input type="checkbox" name="poi_things_options[]"
					id="poi_things_option-<?php echo $key;?>" value=<?php echo $key?> 
					<?php  if(in_array($key, $setvalues))
							 echo "checked"; 
					else echo ''; ?>></td>
<?php
	if ($colnum == $totalcol) {
		$colnum = 0;
		?>
		</tr><?php
		$newrow = true;
	}
}
?>
	
</tbody>
</table>

<?php
$thingsactivity= $form->getElement ( 'poi_things_activity' )->getMultiOptions ();
$setvalues= $form->getElement ( 'poi_things_activity' )->getValue();
if (is_null($setvalues))
        $setvalues=array();
elseif (!is_array($setvalues))
        $setvalues=explode(' ', $setvalues);

if (isset ( $thingsactivity)) {
	$newrow = true;
	$colnum = 0;
	$totalcol = 3;
	$doit = true;
	?>
<h2>Possible Activitites</h2>
	<table>
		<tbody>
<?php

}

foreach ( $thingsactivity as $key => $value ) {
	if ($newrow) {
		$newrow = false;
		?>
		<tr><?php
	}
	$colnum += 1;
	?>
	<td><label for="poi_things_activity-<?php echo $key;?>"><?php echo $value;?></label>
		<input type="checkbox" name="poi_things_activity[]"
					id="poi_things_activity-<?php echo $key;?>" value=<?php echo $key?> 
					<?php  if(in_array($key, $setvalues))
							 echo "checked"; 
					else echo ''; ?>></td>
<?php
	if ($colnum == $totalcol) {
		$colnum = 0;
		?>
		</tr><?php
		$newrow = true;
	}
}
if ($doit) {
	?>
	
</tbody>
</table>

<table>
<tr>
<td>
        <?php echo $form->getElement('submit');?>
</td>
</tr>
</table>

<?php }?>

