<?php
$form = $this->form;
$poi_id=$this->poi_id;
$poi_type=$this->poi_type;
$stay_list=$this->stay_list;
$eat_list=$this->eat_list;
$things_list=$this->things_list;
$related_list=$this->related_list;
$thispoi=$this->thispoi;


?>
<script type="text/javascript">
loadScript(); 
</script>
<a
href="<?= '/poi/generalinfo/'. $poi_id;?>">General Information</a>
<input id="thispoi_lat" name = "thispoi_lat" type="hidden" value="<?php echo $thispoi['poi_lat'];?>">
<input id="thispoi_lon" name = "thispoi_lon" type="hidden" value="<?php echo  $thispoi['poi_lon'];?>">

<!-- Dragable-->
<div id='container'>
<input type="text" name="staysearch" id="staysearch" value=""style="width: 30%;float: left;">
<input type="text" name="eatsearch" id="eatsearch" value="" style="width: 30%;margin-left:  4%">
<input type="text" name="thingssearch" id="thingssearch" value=""style="width: 30%;margin-left:  1%">

<div >
<ul id="staylist" class="poilist" style="display:block; width: 30%; height: 30%; overflow: auto;">
<?php 
$i=0;
foreach ($stay_list as $stay)
{?>
    <li id=<?php echo $stay['poi_id'];?> class="ui-state-default" 
        data-lat=<?php echo $stay['poi_lat']?> data-lon = <?php echo $stay['poi_lon']?>
        style="cursor:move;"><?php echo $stay['poi_name']?></li>
   
    <?php }
    
?>
</ul>
</div>

<div >
<ul id="eatlist" class="poilist"  style="display:block;float:left; width: 30%; height: 30%; overflow: auto;">
<?php 
foreach ($eat_list as $eat)
{?>
    <li id=<?php echo $eat['poi_id'];?> class="ui-state-default" 
        data-lat=<?php echo $eat['poi_lat']?> data-lon = <?php echo $eat['poi_lon']?>
        style="cursor:move;"><?php echo $eat['poi_name']?></li>
    
    <?php }
?>
</ul>
</div>

<div>

<ul id="thingslist" class="poilist" style="float:left; 30%; height: 30%; overflow: auto;">
<?php 
foreach ($things_list as $things)
{?>
    <li id=<?php echo $things['poi_id'];?> class="ui-state-default" 
        data-lat=<?php echo $things['poi_lat']?> data-lon = <?php echo $things['poi_lon']?>
        style="cursor:move;"><?php echo $things['poi_name']?></li>
<?php }
?>
</ul>
</div>
<br style="clear: both;" />
<p></p>

<!-- dropable -->
<div  >
<ul id = "relatedlist" class="droptrue" style="height: 10%; overflow: auto; ">
<?php 
if (!is_array($related_list))
    $related_list=array();
?>
<?php 
foreach ($related_list as $related)
{?>
    <li class="placeholder" style="cursor:move;"><?php echo $related['poi_name']?></li>
<?php }
?>

</ul>
</div>

<div id ='tag_div_helper'></div>
</div>
<div id="map_canvas"></div>

<script>
$(function() {
	var dragops = {
			connectWith: "#relatedlist",
			revert:true,
			};
	var dropops = {
			update: function(event, ui) {
				var poi_lat = ui.item.attr("data-lat");
				var poi_lon = ui.item.attr("data-lon");
				addMarker(poi_lat,poi_lon);
				
				}
			};
			
	$( "#thingslist" ).sortable(dragops);
	$( "#eatlist" ).sortable(dragops);
	$( "#staylist" ).sortable(dragops);
    $( "#relatedlist" ).sortable(dropops);
    
    $("#staysearch").keyup(function(){
        var text = $(this).val();
        $('#staylist li').each(function(){
             if($(this).text().toUpperCase().indexOf(text.toUpperCase()) == -1)
                 $(this).hide();
             else
                $(this).show();});     
    });
    $("#eatsearch").keyup(function(){
        var text = $(this).val();
        $('#eatlist li').each(function(){
            if($(this).text().toUpperCase().indexOf(text.toUpperCase()) == -1)
                $(this).hide();
             else
                $(this).show();});     
    });
    $("#thingssearch").keyup(function(){
        var text = $(this).val();
        $('#thingslist li').each(function(){
            if($(this).text().toUpperCase().indexOf(text.toUpperCase()) == -1)
                $(this).hide();
             else
                $(this).show();});     
    });
});

</script>
<script type="text/javascript">
<!--

//-->
</script>
<style>
    .ui-state-default.hide { display:none; }
    .poilist  { 
    list-style-type: none; 
    margin: 0; 
    padding: 0; 
    float: left; 
    margin-right: 5px; 
    background: #eee; 
    padding: 5px; 
    width: 143px;}
    
    #relatedlist{ 
    list-style-type: none; 
    margin: 0; 
    padding: 0; 
    float: left; 
    margin-right: 10px; 
    background: #eee; 
    padding: 5px; 
    width: 96%;}
    .ui-state-default.hide { display:none; }
    #relatedlist ul li, #poilist ul li  { 
    margin: 5px; 
    padding: 5px; 
    font-size: 1.2em; 
    width: 120px; }
</style>
