<?php
$form = $this->form;
$poi_id=$this->poi_id;
$poi_type=$this->poi_type;
$row=$this->row;
?>

<?php $path='/uploads/poi/'.$this->poi_id.'/';?>
<?php 
foreach ($this->images as $image)
{?>
    <a href="img01_url" target="_blank">
        <img width="100" height="100" src="<?php echo $path.$image['poiimg_path'];?> ">
    </a>    
<?php break;}?>

		
<div class="main-container col2-left-layout">
<div class="main">

<div class="col-main">
<div class="col-main-container">
<div class="dashboard">
<div class = "tab-wrapper">
<div class="index-tabs">
<!-- Tab 1-->	 
<div id="tab-1" class="tab-1">
<div class="container">
        <?php 
        if ($poi_type=='Stay')
        {
            include '_poiStayview.phtml';
        }
        if ($poi_type=='Eat')
        {
            include '_poiEatview.phtml';
        }
        if ($poi_type=='Things')
        {
            include '_poiThingsview.phtml';
        }
        ?>
</div> <!--  container-->
</div> <!--  tab tab-1 tab-active-->
<!-- Tab 2-->	 
<div class="tab-2">
<div id="tab-2" class="container">
        <?php 
        if ($poi_type=='Stay')
        {
        include '_poiStayParamsview.phtml';
        }
        if ($poi_type=='Eat')
        {
            include '_poiEatParamsview.phtml';
        }
        if ($poi_type=='Things')
        {
            include '_poithingsparamsview.phtml';
        }
        ?>
</div>
</div>
<!-- Tab 3-->	 
<div id="tab-3" class="tab-3">
<div class="container">
        <?php include '_poiImagesview.phtml';?>
</div> <!--  container-->
</div> <!--  tab tab-1 tab-active-->

</div>  <!--  index tabs-->
</div> <!--  tab-wrapper-->
</div> <!--  dashboard -->
</div> <!--  col main container -->
</div> <!-- col main  -->





</div>
</div>

<script type="text/javascript">
jQuery(document).ready(function($){
	if(jQuery.browser.msie && $.browser.version < 8) 
		$('input[type=radio],[type=checkbox]').on('click', 
				function(){ $(this).trigger('change'); });
	jQuery('.index-tabs .tab-2 .container').hide();
	jQuery('.index-tabs .tab-3 .container').hide();
	jQuery('.index-tabs .tab-button').click(function(){
		jQuery(this).parents('.index-tabs').find('.tab').each(function(){ 
			jQuery(this).removeClass('tab-active'); $('.container', this).hide(); });
		jQuery(this).next('.container').show();
		jQuery(this).parent('div').addClass('tab-active');
	});
	
});
</script>
		

		

