production:
  phpSettings:
    display_startup_errors: off
    display_errors: off
    date:
      timezone: Europe/Kiev
  includePaths:
    library: APPLICATION_PATH/../library
  pluginPaths:
    Core_Application_Resource: Core/Application/Resource
  bootstrap:
    path: APPLICATION_PATH/bootstrap/Bootstrap.php
    class: Bootstrap
  appnamespace: Application
  autoloadernamespaces:
    - Core
    - SF
    - Facebook
  uploadDir: uploads
  resources:
    frontController:
      moduleDirectory: APPLICATION_PATH/modules
      moduleControllerDirectoryName: controllers
      moduleModelDirectoryName: models
      defaultControllerName: index
      defaultAction: index
      defaultModule: default
      baseUrl: /
      env: APPLICATION_ENV
      params:
        prefixDefaultModule: on
        displayExceptions: off
      actionhelperpaths:
        Helper: APPLICATION_PATH/helpers
      plugins:
        acl:
          class: Core_Controller_Plugin_Acl
          stackindex: 30
          options:
            config: acl
            allowAll: on
            denied:
              module: default
              controller: error
              action: denied
            error:
              module: default
              controller: error
              action: notfound
            login:
              module: users
              controller: login
              action: index
            role: guest
            cache: acl
    router:
      config: routes
      cache: router
#    translate:
#      locale: en
#      scan: filename
#      disableNotices: on
#      logUntranslated: off
#      logMessage: Undefined message '%message%' in '%locale%'
#      logPath: APPLICATION_PATH/../data/logs/lang.log
#    locale: on
#    modules: on
    layout:
      layout: default/layout
      layoutPath: APPLICATION_PATH/layouts/scripts/
#    auth: on
#    registry:
#      fbConfig:
#        appId: 
#        secret: 
#        cookie: on
#      twitterConfig:
#        callbackUrl: /users/login/oauth/type/twitter
#        siteUrl: http://twitter.com/oauth
#        consumerKey: 
#        consumerSecret: 
#      googleConfig:
#        callbackUrl: /users/login/oauth/type/google
#        siteUrl: https://www.google.com/accounts/
#        authorizeUrl: https://www.google.com/accounts/OAuthAuthorizeToken
#        requestTokenUrl: https://www.google.com/accounts/OAuthGetRequestToken
#        accessTokenUrl: https://www.google.com/accounts/OAuthGetAccessToken
#        consumerKey: 
#        consumerSecret: 
#    session:
#      save_path: C:\Zend\Apache2\htdocs\sample\application/../data/session
#    mail:
#      transport:
#        type: Zend_Mail_Transport_Smtp
#        host: localhost
#        port: 25
#      defaultFrom:
#        email: zfc@nixsolutions.com
#        name: ZFCore Webmaster
#    asset:
#      adapter: Core_Asset_Adapter_Simple
#      packages:
#        base:
#          include: PUBLIC_PATH/assets/base/
#          buildDir: PUBLIC_PATH/assets/base/builds/
#        default:
#          include: PUBLIC_PATH/assets/default/
#          buildDir: PUBLIC_PATH/assets/default/builds/
#          extend: base
#        dashboard:
#          include: PUBLIC_PATH/assets/dashboard/
#          buildDir: PUBLIC_PATH/assets/dashboard/builds/
#          extend: base
    view:
      title: sample
      doctype: HTML5
      charset: UTF-8
      encoding: UTF-8
      contentType: text/html; charset=UTF-8
      meta:
        httpEquiv:
          Content-Language: en-US
      helperPath:
        Core_View_Helper: Core/View/Helper
        Application_View_Helper: APPLICATION_PATH/layouts/helpers
        Comments_View_Helper: APPLICATION_PATH/modules/comments/views/helpers
      filterPath:
        Core_View_Filter: Core/View/Filter
        Application_View_Filter: APPLICATION_PATH/layouts/filters
      scriptPath:
        - APPLICATION_PATH/views/scripts
    navigation:
      source:
#        dashboard: config
        default: config
      config: navigation
      cache: navigation
    db:
      adapter: Mysqli
      params:
        host: localhost
        username: root
        password: root
        dbname: hmt
        charset: utf8
testing:
  _extends: production
  phpSettings:
    display_startup_errors: on
    display_errors: on
  resources:
    layout:
      layout: default/layout
    db:
      adapter: Pdo Mysql
      params:
        host: hippo.nixsolutions.com
        username: d_unittest
        password: unittest
        dbname: p_zfc_test
        persistent: on
    frontController:
      defaultModule: index
      plugins:
        acl:
          options:
            allowAll: off
    navigation:
      source:
        dashboard: config
        default: config
      config: navigation
      cache: navigation
development:
  _extends: production
  phpSettings:
    display_startup_errors: on
    display_errors: on
    error_reporting: E_ALL|E_STRICT
  resources:
    frontController:
      params:
        displayExceptions: on
      plugins:
        debug:
          class: Core_Controller_Plugin_Debug
    db:
      params:
        profiler:
          enabled: on
          class: Zend_Db_Profiler_Firebug
