<?php 
$request = Zend_Controller_Front::getInstance()->getRequest();
$class = array();
$class[] = 'm-' . $request->getModuleName();
$class[] = 'c-' . $request->getControllerName();
$class[] = 'a-' . $request->getActionName();
?>
<html>
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<?php
echo $this->headTitle();
$this->headLink()->appendStylesheet('/css/default/layout.css');
$this->headLink()->appendStylesheet('/css/default/text.css');
//$this->loadSkin($this->skin);
echo $this->headLink();
echo $this->headScript();
?>

</head>
<body >
	<div id="header">
		<div id="logo">
			<h1>
				<a href="#">Help me 2 Travel</a>
			</h1>
			<h2>your travel planer</h2>
		</div>
		<div id="menu">
			<ul>
               <?php echo $this->render('default/partial/menu.phtml') ?>
    		</ul>
		</div>
	</div>
	<!-- end #header -->
	<div id="page">
		<!-- start sidebar1 -->
		<div id="sidebar1" class="sidebar">
			<ul>
<?php 
			  if (isset($this->leftbar1title))
                 {?>
           		<li>
			        <h2><?php echo $this->leftbar1title; ?></h2>
			        <ul>
    			        <?php echo $this->render('default/partial/leftmenu1.phtml') ?>
			        </ul>
			    </li>
<?php
                }?>
<?php 
			  if (isset($this->leftbar2title))
                 {?>
           		<li>
			        <h2><?php echo $this->leftbar2title; ?></h2>
			        <ul>
    			        <?php echo $this->render('default/partial/leftmenu2.phtml') ?>
			        </ul>
			    </li>
<?php
                }?>
                
			</ul>
		</div>
		<!-- end sidebar1 -->
		<!-- start content -->
		<div id="content">
			<div class="post">
				<h1><?php echo $this->layout()->menu;?></h1>

				<h1 class="title">
					<a href="#" rel="bookmark" title=""><?php echo $this->title?></a>
				</h1>
				<div class="entry">
	    			<?php echo $this->layout()->content;?>
    			</div>
			</div>
		</div>
		<!-- end content -->
		<!-- start sidebar2 -->
		<div id="sidebar2" class="sidebar">
			<ul>
				<li id="recent-posts">
					<h2>right pan</h2>
					<ul>
						<li>
							<h3>
								<a href="#">Aliquam Libero</a>
							</h3>
						<?php echo $this->layout()->rightbar1;?>
					</li>
					</ul>
			
			</ul>
		</div>
		<!-- end sidebar2 -->
		<div style="clear: both;">&nbsp;</div>
	</div>
	<!-- end page -->
	<div id="footer">
		<p>
			Powered by <a href="http://www.hempme2travel.com/">www.hempme2travel.com</a>
		</p>
	</div>
</body>
</html>
