<!DOCTYPE html>
<?php 
$request = Zend_Controller_Front::getInstance()->getRequest();
$class = array();
$class[] = 'm-' . $request->getModuleName();
$class[] = 'c-' . $request->getControllerName();
$class[] = 'a-' . $request->getActionName();
?>
<html>
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<?php
echo $this->headTitle();
$this->headLink()->appendStylesheet('/css/default/layout.css');
$this->headScript()->appendFile('/js/jquery-1.8.2.js');
$this->headScript()->appendFile('/js/jquery-ui.js');
echo $this->headLink();
echo $this->headScript();
?>

</head>
<body onload="initialize()" class=" cms-index-index cms-home">
<div class="wrapper">
	<noscript>
        <div class="noscript">
            <div class="noscript-inner">
                <p><strong>JavaScript seem to be disabled in your browse.</strong></p>
                <p>You must have JavaScript enabled in your browser to utilize the functionality of this website.</p>
            </div>
        </div>
	</noscript>
<div class="page">
	<div class="header-container">
    	<div class = "top-panel">
    	    <?php echo $this->render('default/partial/topPanel.phtml') ?>
    	</div>
        <div class="header">
	        <header>
 		  	  <a href="\" title="HelpmeTravel" class="logo">Help me Travel</a>
              <div class="nav-container">
    	            <?php echo $this->render('default/partial/mainmenu.phtml') ?>
              </div> <!-- nav-container -->
            </header>
        </div> <!-- header -->
     </div>
<!-- Page body starts here -->
	 <?php echo $this->layout()->content;?>
	 
	 
	 
	 
	 
     <hr>
     
    <footer class="p-footer" >
		<small><b>&copy;Powered by <a href="http://www.hempme2travel.com/">www.hempme2travel.com</a> All Right Reserved. </b></small>
    	
    	<nav>
    		 <ul>
    		   <li class=" news"><a href="" title=""><span>News</span></a></li>
               <li class=" about"><a href="" title="About Us"><span>About Us</span></a></li>
               <li class=" corporate"><a href="" title="Corporate "><span>Corporate &amp; Retail</span></a></li>
               <li class=" faq"><a href="" title="FAQ"><span>FAQ</span></a></li>
               <li class=" agb"><a href="" title=""><span>AGB</span></a></li>
               <li class=" imprint"><a href="" title="dimdim"><span>dim dim</span></a></li>       		
    		</ul>
    	</nav>
    </footer>
</div> <!-- Page  -->
</div> <!-- wrapper -->
    
</body>
</html>
