

<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true&libraries=places"></script>

<script type="text/javascript">
var component_form = {
	    'locality': 'long_name',
	    'country': 'long_name',
	  };
function initialize() 
{
    var input = document.getElementById('poititle');
    var autocomplete = new google.maps.places.Autocomplete(input);
    google.maps.event.addListener(autocomplete, 'place_changed', function() 
            {
            
    	     var place = autocomplete.getPlace();
              document.getElementById('place_name').value= place.name;
              for (var j = 0; j < place.address_components.length; j++) {
                  var att = place.address_components[j].types[0];
                  if (component_form[att]) {
                    var val = place.address_components[j][component_form[att]];
                    document.getElementById(att).value = val;
                  }
                }
              document.getElementById('place_phone').value= place.formatted_phone_number;
              document.getElementById('lat').value= place.geometry.location.lat();
              document.getElementById('lon').value= place.geometry.location.lng();
              document.getElementById('website').value= place.website;
              document.getElementById('type').value= place.types;
              
                
});
}
google.maps.event.addDomListener(window, 'load', initialize);


</script>
<input type="text" name="poititle" id="poititle" size="20" class = "input-text required-entry" placeholder="Enter a location" autocomplete="on"/>
<input type="text" name="place_name" id="place_name" size="20" disabled/>
<input type="text" name="country" id="country" size="20" disabled/>
<input type="text" name="locality" id="locality" size="20" disabled/>
<input type="text" name="place_phone" id="place_phone" size="20" disabled/>
<input type="text" name="lat" id="lat" size="20" disabled/>
<input type="text" name="lon" id="lon" size="20" disabled/>
<input type="text" name="website" id="website" size="20" disabled/>
<input type="text" name="type" id="type" size="20" disabled/>


<h4><a href="<?= ' /poi/addstay';?>">Add a new Stay</a></h4>
<h4><a href="<?='/poi/addeat';?>">Add a new East and Drink</a></h4> 
<h4><a href="<?='/poi/addthings';?>">Add a new Things to do</a></h4> 
<p></p>


<table class="datatable">
	<tbody>
			<? foreach($this->pois as $poi):  ?>        
			<tr>
			<td>
				<h4>
					<a href="<?= '/poi/profile/generalinfo/'.$poi->poi_id;?>">
                        <?=$this->Escape($poi->poi_name); ?></a>
				</h4>
			</td>
			<td><?=$this->Escape($poi->poi_group_name);?></td>
			<td><?=$this->Escape($poi->poi_web_site);?></td>
			<td><?=$this->Escape($poi->poi_stay_type);?></td>
			<td><?=$this->Escape($poi->poi_location_type);?></td>
<!--  makes error in Debug
			
			<td><img alt="abc"
				src="<?php// "/images/poi/".$poi->DefaultImage;?>"></td>
 -->
			<td>/ <a
				href="<?=$this->url ( array ('controller' => 'profile','action' => 'generalinfo','poi_id' => $poi->poi_id ) )?>">Edit</a>
			</td>
		</tr>
        <? endforeach; ?>
    </tbody>
<? if($this->pois instanceof Zend_Paginator): ?>
<?=

	$this->paginationControl ( $this->pois, 'Sliding', 'poi/_paginator.phtml' );
	?>
<? endif ?>
</table>
